package it.objectmethod.tatami.entity.enums;

public enum LogAction {

	END_TURN(0), SKIP_TURN(0), BEGIN_TURN(0), BEGIN_UNLOCK(1), UNLOCK(2), END_UNLOCK(1), BEGIN_EARN(1), EARN(
		2), EMERGENCY_EARN(-1), END_EARN(1), BEGIN_MOVEMENT(1), GAIN_MOVE_ACTIONS(2), GAIN_STEPS(2), MOVE(3), ROTATE(
			3), TRANSLATE(2), PAY(10), PAY_TRANSIT(4), BEGIN_BATTLE(4), CHECK_ADVANTAGE(5), ROLL_BATTLE(
				5), CHECK_WINNER(5), LOCK(10), GAIN_TATAMI(10), LOOSE_TATAMI(10), END_MOVEMENT(1), ACCESS_SHOP(1), DRAW(
					2), BUY_GREEN(3), USE_ACTION(-1), DISCARD_GREEN(-1), END_SHOP(1), LOOSE_GAME(-1), WIN_GAME(
						-1), TELEPORT(10), FULL_UNLOCK(10), DIG(10), STEAL_GREEN(10), STEAL_TATAMI(10), EARNING_GREEN(
							10), USE_EARNING_GREEN(10), REROLL_YOUR_TURN(
								10), REROLL_ONE(10), DIG_PLUS(10), ASK_IF_WIN(100), VOTE_FOR_WIN(100);

	private int actionLevel;

	LogAction(int actionLevel) {
		this.actionLevel = actionLevel;
	}
}
